name: Deploy en Cloud Run

on:
  push:
    branches:
      - main

      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Crear archivo .env para el build
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> .env
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
          echo "GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }}" >> .env
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> .env
          echo "CLERK_SIGN_IN_URL=${{ secrets.CLERK_SIGN_IN_URL }}" >> .env
          echo "CLERK_SIGN_UP_URL=${{ secrets.CLERK_SIGN_UP_URL }}" >> .env
          echo "CLERK_AFTER_SIGN_IN_URL=${{ secrets.CLERK_AFTER_SIGN_IN_URL }}" >> .env
          echo "CLERK_AFTER_SIGN_UP_URL=${{ secrets.CLERK_AFTER_SIGN_UP_URL }}" >> .env
          # Verificar que se creó correctamente
          cat .env | grep -v "SECRET\|URL\|KEY" | cat



      - name: Autenticarse en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Autenticar Docker con Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Construir y enviar imagen a Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ecommerce-gime/gcr.io .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ecommerce-gime/gcr.io 

      - name: Desplegar en Cloud Run
        run: |
          gcloud run deploy mi-app \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ecommerce-gime/gcr.io  \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account github-actions@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com \
            --set-env-vars "NODE_ENV=production" \
            --set-env-vars "NODE_ENV=production,DATABASE_URL=${{ secrets.DATABASE_URL }},NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }},CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}"

      # - name: Ejecutar Migraciones en Cloud SQL
      #   run: |
      #     gcloud run exec mi-app --region=us-central1 -- npx prisma migrate deploy
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}